### ISSUE TITLE
api fixed the locations endpoint

### ISSUE THREAD

**Issue by mustberuss** [ropensci/patentsview#14]
https://github.com/CSSIP-AIR/PatentsView-API/issues/29 has been fixed so cpc_sequence can be added back to the locations endpoint.  I changed fieldsdf.R in my fork and ran it but it says a pr won't automatically merge so I didn't submit it.  It should probably start out as an issue first anyway.

**Comment by crew102** [comment]
Thanks for letting me know. I've updated fieldsdf.R and re-run, so it should be up to date now.
