### ISSUE TITLE
Documentation website returns 404 

### ISSUE THREAD

**Issue by R3myG** [ropensci/patentsview#18]
Hello,

The [getting started](https://docs.ropensci.org/patentsview/articles/getting-started.html), [writing queries ](https://docs.ropensci.org/patentsview/articles/writing-queries.html), [examples](https://docs.ropensci.org/patentsview/articles/examples.html) and [top assignees ](https://docs.ropensci.org/patentsview/articles/top-assignees.html) pages of https://docs.ropensci.org/patentsview/index.html are returning a 404 error. 

Is there any possibility to get those pages back or find them somewhere else?

**Comment by crew102** [comment]
Hi @jeroen , can you advise what's going on here? It looks like you changed the urls in 62fc7d3 to point to one of ropensci's servers (as opposed to a gitHub.io). I'm fine with having the docs hosted elsewhere, but it looks like the atypical way that patentsview creates the html files in docs (e.g., here: https://github.com/ropensci/patentsview/blob/master/inst/site/build-site.R#L25-L34) is causing a problem.

**Comment by jeroen** [comment]
Oh hmm sorry I didn't spot that when I changed the URL. 

Why not use the standard directory structure for articles, such that the site works out of the box? Vignettes that you want to be part of the CRAN package go in `./vignettes` and other articles go in `./vignettes/articles`.

See for example the weathercan package: https://docs.ropensci.org/weathercan/articles/

**Comment by crew102** [comment]
Didn't know that you could put vignettes that shouldn't be included by CRAN in vignettes/articles. I'm fine with moving the vignettes there and updating build-site.R accordingly (so that ropensci's version of the site would presumably include those vignettes in the site), but can we keep the advertised URL as the one hosted by GitHub, not docs.ropensci? I did some customization on it and I'm not sure if those customizations would be incorporated by ropensci's version of the site (I'm not even sure how ropensci creates the site to begin with?)

**Comment by jeroen** [comment]
I think you shouldn't need any `build-site.R` if you use the default structure? The ropensci docs builder uses the standard `pkgdown::build_site()` except we override the theme and add our docsearch api key (that provides the search box). Other than that you should be able to use all `_pkgdown.yml` options.

See also the rotemplate docs: https://docs.ropensci.org/rotemplate/

What sort of customizations would you like to do?

**Comment by crew102** [comment]
When I last worked on this package there was a problem with how pkgdown was rendering some links, so I had to fix the html in `fix_fun_index()` and `remove_cran_href()` (see https://github.com/ropensci/patentsview/blob/master/inst/site/build-site.R#L1). I just re-built the site with those functions commented out (and using a newish version of pkgdown) and everything looks fine, so yeah, I should be able to get rid of build-site. I'll fix it up and close this when I'm done.

**Comment by crew102** [comment]
Hmm, looks like none of the vignettes are now being shown on the site. @jeroen , the site renders correctly and links are correct when I run `pkgdown::build_site()` locally (see results in docs dir). Any idea why the links would not be correct in the docs.ropensci version?

**Comment by jeroen** [comment]
Judging from the log file https://dev.ropensci.org/job/patentsview/62/console the build failed due to a missing package `visNetwork` ...

**Comment by jeroen** [comment]
I have fixed it for you via: https://github.com/ropensci/patentsview/commit/94d987f54a9756e31e62dc408ffa19434681157c

Now it works: https://docs.ropensci.org/patentsview

Btw you can always see the latest status and log files on https://dev.ropensci.org

**Comment by crew102** [comment]
Thanks for fixing that for the info re: Jenkins builds. I noticed that, when building locally with:

```r
template <- list(package = "rotemplate")
pkgdown::build_site(override = list(template = template))
```

...It appears that the styles in pkgdown/extra.css don't get applied. I just have one style that I apply (adding a visible border around code boxes), but I think that it makes the articles a lot more readable. Any way I can override your override of the theme for these elements?

**Comment by mustberuss** [comment]
On https://docs.ropensci.org/patentsview/ the vignette links in the top nav bar work but the ones in the Learning more at the bottom of the page are still 404s.  The ones that work have an extra /articles in the url

https://docs.ropensci.org/patentsview/articles/articles/citation-networks.html
https://docs.ropensci.org/patentsview/articles/articles/examples.html
https://docs.ropensci.org/patentsview/articles/articles/getting-started.html
https://docs.ropensci.org/patentsview/articles/articles/top-assignees.html
https://docs.ropensci.org/patentsview/articles/articles/writing-queries.html

**Comment by crew102** [comment]
Thanks for the heads up @mustberuss . 674bc8d8eb0a17db6e6f7e35ae81cd44447bea82 should fix the issue. Also @jeroen, it looks like ropensci's template has changed to add some background color to code blocks, so the issue I mentioned re: not being able to see the boundaries of these boxes is taken care of.
