### ISSUE TITLE
Need help for master thesis - R - patent applications and citations per firm per year

### ISSUE THREAD

**Issue by andcar284** [ropensci/patentsview#19]
Hi,

I am currently working on my master thesis and came over this package for R which could potentially save me a lot of hours. I have a list of companies collected from the VentureXpert database. For these companies I need yearly (2010, 2011, ... , 2019) amount of patent applications, granted patents, and if possible total amount of forward patent citations (for that company that year). 

Currently, there are 336 firms with 10 firm-years (i = 336, t=10).

As you may understand this will be used to help create my panel data, and as I am measuring innovative performance, the above will be different dependent variables I am looking into. 

Firm 1    Year A    Patents_1A
Firm 1    Year B    Patents_1B
.
.
.
Firm X    Year Y    Patents_XY

So, my question is if anyone could help me with the code for collecting this data with this package? It seems my alternative is to manually go to the USPTO database and search up every firm every year. I do not know how to web scrape. 

Thanks in advance!

**Comment by crew102** [comment]
Hi Andreas,

I actually don't support people on their individual projects, only on specific questions about particular issues/bugs with the patentsview package. You could probably find some freelance coder to do this for you, though. It wouldn't be hard - just point them to the patetsview online documentation/examples and they should be able to get you what you need.

Chris

**Comment by andcar284** [comment]
Hi Chris,

Thank you for your reply! I will continue to look for a solution.

Andreas
