### ISSUE TITLE
Add peer-review badge to the README?

### ISSUE THREAD

**Issue by maelle** [ropensci/patentsview#3]
@crew102 there's now a badge for packages that have been peer-reviewed. The `patentsview` one could be added to the README via

`[![](http://badges.ropensci.org/112_status.svg)](https://github.com/ropensci/onboarding/issues/112)`

In the future these badges will even be added before and during review, they will be automatically updated based on the review progress.

**Comment by crew102** [comment]
Thanks, this badge has been added.
