### ISSUE TITLE
Add retrieve_linked_data to pkgdown reference index configuration

### ISSUE THREAD

**Issue by maelle** [ropensci/patentsview#30]
:wave: @crew102! Happy New Year! We see an error via https://ropensci.r-universe.dev/ui#builds when trying to build docs for this package, and via `pkgdown::check_pkgdown()`.

**Comment by mustberuss** [comment]
Happy New Year Maëlle!  I pushed [9049c4c ](https://github.com/ropensci/patentsview/pull/29/commits/9049c4c2dae02d1d3cfbe16c3209c81c85ba7f86)for this, my PR is to blame.  We'll have to add that check to our workflow.  Thanks and yes, a package is needed for this API!

**Comment by maelle** [comment]
Thank you!
