### ISSUE TITLE
xheader_er_or_status(resp) : Gateway Timeout (HTTP 504)

### ISSUE THREAD

**Issue by Someone894** [ropensci/patentsview#33]
Hello,

currently I am trying to use the `patentsview` R-package to download some data, but I'm having trouble with the API. Here is a MWE which produces an `Error in xheader_er_or_status(resp) : Gateway Timeout (HTTP 504)`:

```R
data <- patentsview::search_pv(
  query = patentsview::qry_funs$contains(assignee_organization = "M System"),
  fields = c(
    "app_number",
    "app_country",
    "app_date",
    "assignee_country",
    "assignee_id",
    "assignee_organization",
    "cited_patent_number",
    "citedby_patent_number",
    "forprior_country",
    "forprior_date",
    "forprior_docnumber",
    "inventor_first_name",
    "inventor_last_name",
    "ipc_class"
  ),
  sort = c("app_date" = "asc"),
  endpoint = "patents",
  all_pages = TRUE
)
```

Is this the expected behaviour or a bug?
How can I download the data if it the expected behaviour, is there some kind of batch mode?
Can you fix the bug, if it is a bug?

**Comment by mustberuss** [comment]
This appears to be an API bug.  A work-around would be to set mtchd_subent_only=FALSE in your search_pv call, the R package defaults it to TRUE.    

Here's a browser call hitting the API directly [that works](https://api.patentsview.org/patents/query?q=%7B%22_contains%22%3A%7B%22assignee_organization%22%20%3A%20%22M%20System%22%7D%7D&f=%5B%22app_number%22%2C%20%20%20%20%20%22app_country%22%2C%20%20%20%20%20%22app_date%22%2C%20%20%20%20%20%22assignee_country%22%2C%20%20%20%20%20%22assignee_id%22%2C%20%20%20%20%20%22assignee_organization%22%2C%20%20%20%20%20%22cited_patent_number%22%2C%20%20%20%20%20%22citedby_patent_number%22%2C%20%20%20%20%20%22forprior_country%22%2C%20%20%20%20%20%22forprior_date%22%2C%20%20%20%20%20%22forprior_docnumber%22%2C%20%20%20%20%20%22inventor_first_name%22%2C%20%20%20%20%20%22inventor_last_name%22%2C%20%20%20%20%20%22ipc_class%22%20%5D&o=%7B%22per_page%22%3A2000%2C%22matched_subentities_only%22%3A%22false%22%7D&s=%5B%7B%22app_date%22%20%3A%22asc%22%7D%5D) and [one that fails](https://api.patentsview.org/patents/query?q=%7B%22_contains%22%3A%7B%22assignee_organization%22%20%3A%20%22M%20System%22%7D%7D&f=%5B%22app_number%22%2C%20%20%20%20%20%22app_country%22%2C%20%20%20%20%20%22app_date%22%2C%20%20%20%20%20%22assignee_country%22%2C%20%20%20%20%20%22assignee_id%22%2C%20%20%20%20%20%22assignee_organization%22%2C%20%20%20%20%20%22cited_patent_number%22%2C%20%20%20%20%20%22citedby_patent_number%22%2C%20%20%20%20%20%22forprior_country%22%2C%20%20%20%20%20%22forprior_date%22%2C%20%20%20%20%20%22forprior_docnumber%22%2C%20%20%20%20%20%22inventor_first_name%22%2C%20%20%20%20%20%22inventor_last_name%22%2C%20%20%20%20%20%22ipc_class%22%20%5D&o=%7B%22per_page%22%3A2000%2C%22matched_subentities_only%22%3A%22true%22%7D&s=%5B%7B%22app_date%22%20%3A%22asc%22%7D%5D) with a gateway timeout, the difference being their matched_subentities_only options parameter.

You could try reporting the bug to the API team but they're trying to sunset this version of the API.  The R package is using the [Legacy Endpoints](https://patentsview.org/apis/api-endpoints/patents) .  The new version of the API is not yet stable and does not have a matched_subentities_only option.  

As a heads up, the new version of the API is quite different than the current one, requiring an API key and other breaking changes so when the R package is updated it will not be backward compatible.

**Comment by Someone894** [comment]
@mustberuss Thenak you for the headsup and also the workaround.
Its sems to me the best is to use the `mtchd_subent_only=FALSE` and wait for the new API to be relased.
Im closing this issue now.
