### ISSUE TITLE
Regarding API 

### ISSUE THREAD

**Issue by krutikaparab9392** [ropensci/patentsview#6]
I am a beginner in R. I followed the documentation that you have provided but I find it difficult to unnest the data.  Can you please give a simple example of how to unnest the data. I want to see the result in tabular format.

**Comment by crew102** [comment]
Did you see this:

https://ropensci.github.io/patentsview/articles/getting-started.html#how-do-i-access-the-data-frames-inside-of-the-subentity-list-columns
