### ISSUE TITLE
Unexposed fields?

### ISSUE THREAD

**Issue by mustberuss** [ropensci/patentsview#7]
[addme.txt](https://github.com/ropensci/patentsview/files/1584313/addme.txt)
Hi, I'm a first time issue creator who's hoping I'm doing this correctly.

Someone posted in the [patentsview api forum](http://www.patentsview.org/community/forum/7/topic/84 ) that the examiner_id is not present.  It's a moderated list so my reply doesn't show up yet but I think the problem is here.  The api does return the field in a [browser request](http://www.patentsview.org/api/patents/query?q=%7B%22_lte%22%3A%7B%22patent_date%22%3A%222017-12-01%22%7D%7D&f=%5B%22patent_number%22%2C%22patent_title%22%2C%22examiner_id%22%2C%22examiner_last_name%22%2C%22examiner_first_name%22%2C%22examiner_role%22%2C%22examiner_group%22%5D) or in R doing a get on the endpoint. It's always coming back as null which is an api issue but shouldn't it be accessible in this package? I got the same error the poster got with the stable and dev packages.

I wrote a perl script to scrape and compare the api's endpoint pages to fieldsdf.csv  It shows that the examiner fields are missing in fieldsdf.csv for all 7 endpoints.  I've attached the fields my script thinks are missing.  I could fork or pull something if this is an issue

github and R novice

**Comment by crew102** [comment]
Greetings @mustberuss, thanks for the heads up. Yes, regarding the fact that it shouldn't be coming back as null in your browser (perhaps open up an issue here for that: https://github.com/CSSIP-AIR/PatentsView-API), and yes, the `patentsview` r package should nevertheless be passing those nulls along. You can re-run the [script](https://github.com/ropensci/patentsview/blob/master/data-raw/fieldsdf.R) that pulls the latest fields from the API's website (as I just have) and open a PR request for the package to update the fields. The dev version of `patentsview` should work for you now.

**Comment by mustberuss** [comment]
@crew102, that is too cool!  You are correct, my dev version is working now.  PR opened.
